FROM node:18.20.4 as build

USER node
WORKDIR /home/node/app

# local install
COPY --chown=node:node package.json .
COPY --chown=node:node package-lock.json .
RUN npm install
# RUN npm install --only=prod

# copy source
COPY --chown=node:node . .
RUN npm run docs:build

# Deploy
FROM nginx:1.23.3 as deploy

COPY --from=build /home/node/app/.vitepress/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]