version: '3.7'
name: ${PROJECT_NAME}
services:
  docs:
    hostname: docs
    restart: always
    ports:
      - 5173:5173
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
